version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=makerdao
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=EcosystemApi
    ports:
      - "5444:5432"
    volumes:
      - db:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
  api:
    image: makerdao/ecosystem-api:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Default=Host=db;Port=5432;Database=EcosystemApi;Username=makerdao;Password=pwd
    depends_on:
      - db
volumes:
  db:
    driver: local
