services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=makerdao
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=EcosystemApi
    ports:
      - "5444:5432"
    volumes:
      - db:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
  redis:
    image: redis/redis-stack
    restart: always
    environment:
      - REDIS_ARGS=--requirepass password --user username on >password ~* allcommands --user default off nopass nocommands
    ports:
      - "8001:8001"
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  db:
    driver: local
  redis:
